name: 'credit_risk_analysis'
version: '1.3.3'
config-version: 2

model-paths: ["models"]  
snapshot-paths: ["snapshots"]
seed-paths: ["seeds"]
test-paths: ["test"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"

models:
  credit_risk_analysis:
  
    staging:  
      +materialized: view
      +tags: ['staging']
      +persist_docs:
        relation: true
        columns: true

    intermediate: 
      +materialized: table
      +tags: ['intermediate']
      +persist_docs:
        relation: true
        columns: true
  
          
    mart:  
      +materialized: table
      +tags: ['mart']
      +persist_docs:
        relation: true
        columns: true

snapshots:
  credit_risk_analysis:
    +target_schema: snapshots
    +strategy: check
    +unique_key: CUSTOMER_ID
    +check_cols: all




    
