with cleaned as(
  select
  ABS(COALESCE(TRY_CAST(TRIM(AGE) AS INT), 0),
  COALESCE(TRIM(CITY), 'NA'),
  COALESCE(TRIM(GENDER), 'NA'),
  ABS(COALESCE(TRY_CAST(TRIM(INCOME) AS NUMERIC(10,3)), 0)),
  ABS(COALESCE(TRY_CAST(TRIM(CIBIL_SCORE) AS INT), 0)),	
  ABS((TRY_CAST(COALESCE(TRY_CAST(TRIM(CUSTOMER_ID) AS INT), 0)),
  ABS(COALESCE(TRY_CAST(TRIM(LOAN_AMOUNT) AS NUMERIC(10,2)), 0)),
  COALESCE(TRIM(LOAN_STATUS), 'NA'),
  COALESCE(TRIM(COMPANY_TYPE), 'NA'),
  COALESCE(TRIM(LOAN_PURPOSE), 'NA'),
  ABS(COALESCE(TRY_CAST(TRIM(INTEREST_RATE) AS NUMERIC(9,7)), 0)),
  ABS(COALESCE(TRY_CAST(TRIM(EXISTING_LOANS) AS INT), 0)),
  COALESCE(TRIM(EMPLOYMENT_STATUS), 'NA'),
  COALESCE(TRY_CAST(TRIM(LOAN_TENURE_MONTHS) AS INT), 0),
  ABS(COALESCE(TRY_CAST(TRIM(DEBT_TO_INCOME_RATIO) AS NUMERIC(8,7)),	0)),
 

  from {{ source('source_credit_risk_analysis', 'SHEET1') }}
  )
  SELECT * FROM cleaned
