with cleaned_and_renamed as(
  
  select
 ABS(COALESCE(TRY_CAST(TRIM(CUSTOMER_ID) AS INT), 0)) AS CUSTOMER_ID,
  ABS(COALESCE(TRY_CAST(TRIM(AGE) AS INT), 0)) AS AGE,
  COALESCE(TRIM(GENDER), 'NA') AS GENDER,
  COALESCE(TRIM(CITY), 'NA') AS CITY,
  COALESCE(TRIM(EMPLOYMENT_STATUS), 'NA') AS EMPLOYMENT_STATUS,
  COALESCE(TRIM(COMPANY_TYPE), 'NA') AS COMPANY_TYPE,
  ABS(COALESCE(TRY_CAST(TRIM(INCOME) AS NUMERIC(10,3)), 0)) AS INCOME,
  ABS(COALESCE(TRY_CAST(TRIM(CIBIL_SCORE) AS INT), 0)) AS CIBIL_SCORE,	
  ABS(COALESCE(TRY_CAST(TRIM(LOAN_AMOUNT) AS NUMERIC(10,2)), 0)) AS LOAN_AMOUNT,
  ABS(COALESCE(TRY_CAST(TRIM(INTEREST_RATE) AS NUMERIC(9,7)), 0)) AS INTEREST_RATE,
  COALESCE(TRY_CAST(TRIM(LOAN_TENURE_MONTHS) AS INT), 0) AS LOAN_TENURE_MONTHS,
  ABS(COALESCE(TRY_CAST(TRIM(EXISTING_LOANS) AS INT), 0)) AS EXISTING_LOANS,
  ABS(COALESCE(TRY_CAST(TRIM(DEBT_TO_INCOME_RATIO) AS NUMERIC(8,7)),	0)) AS DEBT_TO_INCOME_RATIO,
  COALESCE(TRIM(LOAN_PURPOSE), 'NA') AS LOAN_PURPOSE,
COALESCE(TRIM(LOAN_STATUS), 'NA') AS LOAN_STATUS
 
  from {{ source('source_credit_risk_analysis', 'SHEET1') }}
  )
  SELECT * FROM cleaned_and_renamed
