SELECT
  
CASE
WHEN f.CIBIL_SCORE <= 600 THEN 'Poor (<=600)'
WHEN f.CIBIL_SCORE <= 700 THEN 'Average (601-700)'
WHEN f.CIBIL_SCORE <= 750 THEN 'Good (701-750)'
ELSE 'Excellent (>751)'
END AS CIBIL_RANGE,

COUNT_IF (l.LOAN_STATUS = 'Default') * 100 / COUNT(*) AS DEFAULT_RATE,

COUNT_IF (l.LOAN_STATUS = 'Default') AS TOTAL_DEFAULT_CUSTOMERS
  

FROM {{ ref('fact_credit_risk_analysis') }} f
JOIN {{ ref('dim_loan_profile') }} l
ON f.CUSTOMER_ID = l.CUSTOMER_ID

GROUP BY CIBIL_RANGE
ORDER BY CIBIL_RANGE DESC

