SELECT
e.EMPLOYMENT_STATUS,
COUNT(*) AS TOTAL_CUSTOMERS,
COUNT_IF(l.LOAN_STATUS='Default') AS DEFAULT_CUSTOMERS,
ROUND(COUNT_IF(l.LOAN_STATUS='Default')*100.00 / COUNT(*), 2) AS DEFAULT_RATE
FROM {{ ref('dim_loan_profile') }} l
INNER JOIN {{ ref('dim_employment') }} e
ON l.CUSTOMER_ID = e.CUSTOMER_ID
GROUP BY e.EMPLOYMENT_STATUS 
