SELECT
CITY,
LOAN_PURPOSE,
COUNT(*) AS TOTAL_CUSTOMERS,
COUNT_IF(LOAN_STATUS='Default') AS DEFAULT_CUSTOMERS,
ROUND(COUNT_IF(LOAN_STATUS='Default')*100.00 / COUNT(*), 2) AS DEFAULT_RATE
FROM {{ ref('int_customer_loans') }}
