SELECT 
  COUNT(c.CUSTOMER_ID) AS TOTAL_CUSTOMERS, 
  COUNT_IF(c.LOAN_STATUS='Default') AS DEFAULT_CUSTOMERS,
ROUND((COUNT_IF(c.LOAN_STATUS='Default') *100)/  COUNT(c.CUSTOMER_ID), 2) AS DEFAULT_RATE
FROM {{ ref('dim_credit_profile') }}
