SELECT
  
CASE
WHEN f.CIBIL_SCORE < 600 THEN 'Poor (<600)'
WHEN f.CIBIL_SCORE < 700 THEN 'Average (600-699)'
WHEN f.CIBIL_SCORE < 750 THEN 'Good (700-749)'
WHEN f.CIBIL_SCORE BETWEEN 750 AND 800 THEN 'Strong (750-800)'
ELSE 'Excellent (>800)'
END AS CIBIL_RANGE,

COUNT_IF (l.LOAN_STATUS = 'Default') * 100 / COUNT(*) AS DEFAULT_RATE,

COUNT_IF (l.LOAN_STATUS = 'Default') AS TOTAL_DEFAULT_CUSTOMERS
  

FROM {{ ref('fact_credit_risk_analysis') }} f
JOIN {{ ref('dim_loan_profile') }} l
ON f.CUSTOMER_ID = l.CUSTOMER_ID

GROUP BY CIBIL_RANGE
ORDER BY CIBIL_RANGE ASC

