SELECT
c.CUSTOMER_ID,
f.CIBIL_SCORE,
e.INCOME,
f.DEBT_TO_INCOME_RATIO,

  
  CASE
WHEN f.CIBIL_SCORE <= 600 THEN 'Poor (<=600)'
WHEN f.CIBIL_SCORE <= 700 THEN 'Average (601-700)'
WHEN f.CIBIL_SCORE <= 750 THEN 'Good (701-750)'
ELSE 'Excellent (>751)'
  END AS CIBIL_BUCKET,

CASE
    WHEN e.INCOME <= 300000 THEN 'Poor_Income'
    WHEN e.INCOME <= 500000 THEN 'Medium_Income'
  WHEN e.INCOME <= 800000 THEN 'High_Income'
    ELSE 'Excellent_INCOME'
  END AS INCOME_BUCKET,

  CASE
   WHEN f.DEBT_TO_INCOME_RATIO > 0.700000 THEN 'Highly_Risky'
  WHEN f.DEBT_TO_INCOME_RATIO > 0.600000 THEN 'Risky'
  ELSE 'No_Risk'
  END AS DTI_RISK_BUCKET,

  CASE
  WHEN f.CIBIL_SCORE < 600
  OR e.INCOME < 300000
  OR f.DEBT_TO_INCOME_RATIO > 0.700000
  THEN 'High_Risk'

  WHEN f.CIBIL_SCORE < 700
  OR e.INCOME < 450000
   OR f.DEBT_TO_INCOME_RATIO > 0.600000
  THEN 'Risky'

  ELSE 'No_Risk'
  END AS FINAL_RISK_FLAG
  

FROM {{ ref('fact_credit_risk_analysis') }} f
 JOIN {{ ref('dim_customer') }} c
  ON f.CUSTOMER_ID = c.CUSTOMER_ID

 JOIN {{ ref('dim_employment') }} e
  ON f.CUSTOMER_ID = e.CUSTOMER_ID

