SELECT
  
CASE
   WHEN f.LOAN_AMOUNT < 200000 THEN 'Low-Loan_Amount'
   WHEN f.LOAN_AMOUNT < 500000 THEN 'Average_Loan_Amount'
   WHEN f.LOAN_AMOUNT < 750000 THEN 'High_Loan_Amount'
   ELSE 'Highest_Loan_Amount'
END AS LOAN_BUCKET,

 CASE 
    WHEN f.INTEREST_RATE BETWEEN 20 AND 24 THEN 'Highest_Roi'
    WHEN f.INTEREST_RATE BETWEEN  15 AND 19 THEN 'High_Roi'
    WHEN f.INTEREST_RATE BETWEEN 10 AND 14 THEN 'Average_Roi'
    ELSE 'Min_Roi'
  END AS ROI_BUCKET,

CASE
   WHEN f.LOAN_TENURE_MONTHS < 24 THEN 'Low-Tenure'
   WHEN f.LOAN_TENURE_MONTHS < 48 THEN 'Average_Tenure'
   WHEN f.LOAN_TENURE_MONTHS < 60 THEN 'High_Tenure'
   ELSE 'Highest_Tenure'
END AS TENURE_BUCKET,

    CASE 
    WHEN f.CIBIL_SCORE < 600 THEN 'Poor'
    WHEN f.CIBIL_SCORE < 700 THEN 'Average'
    WHEN f.CIBIL_SCORE < 750 THEN 'Good'
    WHEN f.CIBIL_SCORE BETWEEN 750 AND 800 THEN 'Strong'
    ELSE 'Excellent'
  END AS CIBIL_BUCKET,

CASE
   WHEN f.DEBT_TO_INCOME_RATIO < 0.300000 THEN 'Low-Dti'
   WHEN f.DEBT_TO_INCOME_RATIO < .500000 THEN 'Average_Dti'
   WHEN f.DEBT_TO_INCOME_RATIO < .650000 THEN 'High_Dti'
   ELSE 'Highest_Dti'
END AS DTI_BUCKET,

COUNT(*) AS TOTAL_CUSTOMERS,
COUNT_IF( l.LOAN_STATUS = 'Default') AS TOTAL_DEFAULT_CUSTOMERS,

COUNT_IF ( l.LOAN_STATUS = 'Default') * 1.0 / COUNT(*) AS DEFAULT_RATE

FROM {{ ref('fact_credit_risk_analysis') }} f
  JOIN {{ ref('dim_loan_profile') }} l
  ON f.CUSTOMER_ID = l.CUSTOMER_ID

  GROUP BY LOAN_BUCKET, ROI_BUCKET, TENURE_BUCKET, DTI_BUCKET
  ORDER BY DEFAULT_RATE ASC







