
SELECT
  CASE
  WHEN l.EXISTING_LOANS >= 2 AND f.DEBT_TO_INCOME_RATIO >= 0.6000 THEN 'HIGH_RISK_BURDEN_CUSTOMERS'
  ELSE 'OTHERS'
  END AS HIGH_RISK_BURDEN_DEFAULTERS,
  COUNT(*) AS TOTAL_CUSTOMERS,
  COUNT_IF(l.LOAN_STATUS='Default') AS DEFAULT_CUSTOMERS,
  ROUND(COUNT_IF(l.LOAN_STATUS='Default')*100.0000 / COUNT(*), 4) AS DEFAULT_RATE
FROM {{ ref('fact_credit_risk_analysis') }} f
INNER JOIN {{ ref('dim_loan_profile') }} l
ON f.CUSTOMER_ID = l.CUSTOMER_ID

INNER JOIN {{ ref('dim_employment') }} e
ON f.CUSTOMER_ID = e.CUSTOMER_ID

group by HIGH_RISK_BURDEN_DEFAULTERS

 
